### ISSUE TITLE
Question: What are some use cases for and advantages of this preset?

### ISSUE THREAD

**Issue by jhildenbiddle** [playwright-community/jest-playwright-jsdom#1]
I am unclear on the use cases and/or advantages of using this preset. If the intention is to write tests using jsdom instead of a real browser, why use Playwright at all?

I'm just getting started with Playwright, so apologies if I'm missing something obvious. My reason for asking the question is determine if this preset is something I should consider adding to our Jest configuration which uses jest-playwright only for e2e tests by using Jest's [`projects`](https://jestjs.io/docs/en/configuration#projects-arraystring--projectconfig) option:

* https://github.com/docsifyjs/docsify/blob/jest-playwright/jest.config.js

Perhaps adding a brief description of the use case(s) to the `README.md` would be helpful.

Thanks!

**Comment by mxschmitt** [comment]
I agree, I have to admit, that I also don't know the benefit of using this. @mmarkelov can you maybe outline it and if possible add an example?

Thanks for filing this issue!

**Comment by mmarkelov** [comment]
Thanks for the question. Originally it came from here https://github.com/playwright-community/jest-playwright/issues/115
To be honest I don't have any thoughts why it can be helpful. Maybe if you have some unit tests that using **jsdom** and you don't want to change them. But it's very strange case.  So this package can be unnecessary, cause I'm agree that it doesn't have much sense to have **jsdom** and **playwright**

**Comment by jhildenbiddle** [comment]
Is the intention to make jsdom globals (e.g., `window`, `document`, etc.) available in a jest-playwright environment so that Jest + JSDom tests and Jest + Playwright tests can co-exist in the same file?

```js
test('jest + jsdom', async () => {
  document.body.classList.add('foo');
  expect(document.body.getAttribute('class')).toEqual('foo');
});

test('jest + playwright', async () => {
  await page.$eval('body', elm => elm.classList.add('foo'));
  expect(await page.getAttribute('body', 'class')).toEqual('foo');
});
```

If so, perhaps the use case is for projects that also want to run unit and/or integration tests using both jsdom and playwright for both speed and compatibility purposes: enjoy the speed of use jsdom with basic, low-risk DOM-related tests and the confidence that comes from testing with playwright (i.e., in real browsers) for more advanced, higher-risk browser-related tests?

If not, perhaps just a description of what this preset does (instead of use cases and/or advantages) would be helpful. Currently, it's just 🤷 .

**Comment by trusktr** [comment]
It seems like that's the case @jhildenbiddle, and indeed would be helpful for what you described.

**Comment by mxschmitt** [comment]
Definitely such a feature would be nice! Like rendering React components in a real browser for example.
But something like that is not yet working. :/

**Comment by jhildenbiddle** [comment]
Closing this issue since the introduction of Playwright Test (a separate runner) makes this question moot.

**Comment by piotrpalek** [comment]
I'm also unclear on how this should be used, can I use this preset if I want my integration tests to run in firefox/chromium instead of jsdom? Or does this preset run the tests in jsdom?
